#@ load("@ytt:data", "data")
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: tap-install
      version: "3.0.3"
  interval: 1m0s
  values:
    proxy:
      service:
        type: "ClusterIP"
    scheduling:
      userScheduler:
        enabled: false
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jupyter
spec:
  virtualhost:
    fqdn: #@ "jupyterhub-" + data.values.name + ".mlops.tanzu.corby.page"
    tls:
      secretName: contour-tls/tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: proxy-public
          port: 80