#@ load("@ytt:data", "data")
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: jupyterhub
spec:
  serviceAccountName: jupyterhub-helm-sa
  fetch:
    - helmChart:
        name: jupyterhub
        version: "3.0.3"
        repository:
          url: https://hub.jupyter.org/helm-chart/
  template:
    - helmTemplate:
        kubernetesVersion: {}
        valuesFrom:
          - secretRef:
              name: jupyter-values
  deploy:
    - kapp:
        delete:
          #! Force delete PVCs, since StatefulSet does not delete them
          rawOptions: ["--apply-ignored=true"]
---
apiVersion: v1
kind: Secret
metadata:
  name: jupyter-values
stringData:
  data.yml: |
    proxy:
      service:
        type: "ClusterIP"
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jupyter
spec:
  virtualhost:
    fqdn: #@ "jupyterhub-" + data.values.name + ".mlops.tanzu.corby.page"
    tls:
      secretName: contour-tls/tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: proxy-public
          port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-helm-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-helm-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: jupyterhub-helm-sa


