---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  chart:
    spec:
      chart: argo-workflows
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: tap-install
      version: "0.33.3"
  interval: 1m0s
  values:
    server:
      extraArgs:
      - --auth-mode=server
    workflow:
      serviceAccount:
        create: true
        name: "argo-workflow"
      rbac:
        create: true
    controller:
      workflowNamespaces:
        - default
        - argo-workflows
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argo
spec:
  virtualhost:
    fqdn: argo.mlops.tanzu.corby.page
    tls:
      secretName: contour-tls/tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: argo-server
          port: 2746
