---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: argo-workflows
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: argo-workflows-helm-repo
spec:
  interval: 5m0s
  url: https://argoproj.github.io/argo-helm
