---
apiVersion: v1
kind: Namespace
metadata:
  name: datahub
---
apiVersion: v1
data:
  mysql-root-password: ZGF0YWh1Yg==
kind: Secret
metadata:
  name: mysql-secrets
  namespace: datahub
type: Opaque
---
#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: prerequisites
#  namespace: datahub
#spec:
#  chart:
#    spec:
#      chart: datahub-prerequisites
#      sourceRef:
#        kind: HelmRepository
#        name: datahub
#        namespace: tap-install
#      version: "0.0.18"
#  interval: 1m0s
