---
apiVersion: v1
kind: Namespace
metadata:
  name: datahub
---
apiVersion: v1
data:
  mysql-root-password: ZGF0YWh1Yg==
kind: Secret
metadata:
  name: mysql-secrets
  namespace: datahub
type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prerequisites
  namespace: datahub
spec:
  chart:
    spec:
      chart: datahub-prerequisites
      sourceRef:
        kind: HelmRepository
        name: datahub
        namespace: tap-install
      version: "0.0.18"
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datahub
  namespace: datahub
spec:
  chart:
    spec:
      chart: datahub
      sourceRef:
        kind: HelmRepository
        name: datahub
        namespace: tap-install
      version: "0.2.185"
  interval: 1m0s
  values:
    # See https://raw.githubusercontent.com/acryldata/datahub-helm/master/charts/datahub/values.yaml
    datahub-frontend:
      service:
        type: ClusterIP
    datahub-gms:
      service:
        type: ClusterIP
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: datahub
  namespace: datahub
spec:
  virtualhost:
    fqdn: datahub.mlops.tanzu.corby.page
    tls:
      secretName: contour-tls/tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: datahub-datahub-frontend
          port: 9002
