---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: flux-helm-controller
  namespace: tap-install
spec:
  serviceAccountName: tanzu-cd
  packageRef:
    refName: fluxcd-helm-controller.tanzu.vmware.com
    versionSelection:
      constraints: 0.28.1+vmware.1-tkg.2