---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jupyterhub
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: jupyterhub-helm-repo
spec:
  interval: 5m0s
  url: https://hub.jupyter.org/helm-chart
