---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: j-test
  namespace: default
spec:
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: tap-install
      version: "3.0.3"
  interval: 1m0s
  values:
    scheduling:
      userScheduler:
        enabled: false
    proxy:
      service:
        type: "ClusterIP"
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: jupyter
  namespace: default
spec:
  virtualhost:
      fqdn: j-test.mlops.tanzu.corby.page
  routes:
    - conditions:
        - prefix: /
      services:
        - name: proxy-public
          port: 80