---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: minio-helm-repo
spec:
  interval: 5m0s
  url: https://operator.min.io/
