---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  chart:
    spec:
      chart: minio-operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: tap-install
      version: "5.0.8"
  interval: 1m0s

