---
apiVersion: v1
kind: Namespace
metadata:
  name: minio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: tap-install
      version: "5.0.8"
  interval: 1m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio
spec:
  chart:
    spec:
      chart: tenant
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: tap-install
      version: "5.0.8"
  interval: 1m0s
  values:
    tenant:
      name: mlops-tenant
      pools:
        ## Servers specifies the number of MinIO Tenant Pods / Servers in this pool.
        ## For standalone mode, supply 1. For distributed mode, supply 4 or more.
        ## Note that the operator does not support upgrading from standalone to distributed mode.
        - servers: 1
          ## custom name for the pool
          name: pool-0
          ## volumesPerServer specifies the number of volumes attached per MinIO Tenant Pod / Server.
          volumesPerServer: 4
          ## size specifies the capacity per volume
          size: 10Gi
          ## storageClass specifies the storage class name to be used for this pool
          ### If using Amazon Elastic Block Store (EBS) CSI driver
          ### Please make sure to set xfs for "csi.storage.k8s.io/fstype" parameter
          ### under StorageClass.parameters.
          ### Docs: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md
          storageClassName: gp2
          ## Used to specify annotations for pods
          annotations: { }
          ## Used to specify labels for pods
          labels: { }
          ## Used to specify a toleration for a pod
          tolerations: [ ]
          ## nodeSelector parameters for MinIO Pods. It specifies a map of key-value pairs. For the pod to be
          ## eligible to run on a node, the node must have each of the
          ## indicated key-value pairs as labels.
          ## Read more here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
          nodeSelector: { }
          ## Affinity settings for MinIO pods. Read more about affinity
          ## here: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity.
          affinity: { }
          ## Configure resource requests and limits for MinIO containers
          resources: { }
          ## Configure Pod's security context
          ## We recommend to skip the recursive permission change by using
          ## fsGroupChangePolicy as OnRootMismatch because it can be pretty
          ## expensive for larger volumes with lots of small files.
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
          ## Configure container security context
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
          ## Configure topology constraints
          topologySpreadConstraints: [ ]
          ## Configure Runtime Class
          # runtimeClassName: ""
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: minio
  namespace: minio
spec:
  virtualhost:
    fqdn: minio.mlops.tanzu.corby.page
    tls:
      secretName: contour-tls/tls
  routes:
    - conditions:
        - prefix: /
      services:
        - name: mlops-tenant-console
          port: 9443
