---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mlflow
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: mlflow-helm-repo
spec:
  interval: 5m0s
  url: https://community-charts.github.io/helm-charts
