---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mlflow
  namespace: mlflow
spec:
  chart:
    spec:
      chart: mlflow
      sourceRef:
        kind: HelmRepository
        name: mlflow
        namespace: tap-install
      version: "0.7.19"
  interval: 1m0s
  values:
    # See https://raw.githubusercontent.com/community-charts/helm-charts/main/charts/mlflow/values.yaml
    backendStore:
      databaseConnectionCheck: true
      mysql:
        enabled: true
        host: "10.100.26.82"
        port: 3306
        database: "mlflow"
        user: "root"
        password: "4en68agocp3g4atodwxf9k2p1bavlzlq"
    artifactRoot:
      azureBlob:
        enabled: true
        container: "mlflow"
        storageAccount: "cs2fd2a353d1c2cx431bx9d6"
        accessKey: "EgdacYl1KgPYOP4l6TCXkpO2faK0vA1HkopVfhka9SuZX5fDYESyIHlbZFIUmmeEP0eKTQQ8ozgAckNT3PIWFQ=="
#---
#apiVersion: projectcontour.io/v1
#kind: HTTPProxy
#metadata:
#  name: mlflow
#  namespace: mlflow
#spec:
#  virtualhost:
#    fqdn: mlflow.mlops.tanzu.corby.page
#    tls:
#      secretName: contour-tls/tls
#  routes:
#    - conditions:
#        - prefix: /
#      services:
#        - name: http
#          port: 5000
