---
tap_install:
  values:
    profile: full

    shared:
      ingress_domain: mlops.tanzu.corby.page
      ingress_issuer: ""
      image_registry:
        project_path: gcr.io/fe-cpage/tap
        username: _json_key
      kubernetes_version: 1.25.9

    ceip_policy_disclosed: true

    cnrs:
      default_tls_secret: contour-tls/tls
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}" # this is a go-template

    # These packages will be deprecated in future versions of TAP, so we will exclude them to free up space on the cluster
    excluded_packages:
      - learningcenter.tanzu.vmware.com
      - workshops.learningcenter.tanzu.vmware.com
      - eventing.tanzu.vmware.com

    supply_chain: testing_scanning

    metadata_store:
      app_service_type: ClusterIP
      ns_for_export_app_cert: "*"

    grype:
      targetImagePullSecret: registry-credentials

    ootb_supply_chain_testing_scanning:
      gitops:
        ssh_secret: git-https
        branch: main
        commit_message: "Update from TAP Supply Chain Choreographer"
        server_address: https://github.com/
        repository_owner: cpage-pivotal
        repository_name: tap-deliveries

    package_overlays:
      - name: ootb-supply-chain-testing-scanning
        secrets:
          - name: supply-chain-overlay

    namespace_provisioner:
      controller: false
      sync_period: 30s
      # configure a repo that defines which namespaces should exist
      # for simplicity, it's the same one we have been using
      gitops_install:
        ref: origin/main
        subPath: clusters/workshop/cluster-config/namespace-provisioner/namespaces
        url: https://github.com/Tanzu-Solutions-Engineering/mlops-clusters
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
      additional_sources:
        # additional sources points to the resources we want to fill those namespaces with
        - git:
            url: https://github.com/Tanzu-Solutions-Engineering/mlops-clusters
            ref: origin/main
            subPath: clusters/workshop/cluster-config/namespace-provisioner/namespace-resources
            secretRef:
              name: git-https # this is the new credential
              namespace: tap-install
      default_parameters:
        supply_chain_service_account:
          secrets:
            - git-https

    local_source_proxy:
      repository: gcr.io/fe-cpage/tap-source-proxy
      push_secret:
        name: lsp-push-credentials
        namespace: tap-install
        create_export: true

    tap_gui:
      tls:
        namespace: contour-tls
        secretName: tls
      service_type: ClusterIP
      ingressEnabled: "true"
      metadataStoreAutoconfiguration: true
      app_config:
        auth:
          allowGuestAccess: true
          environment: development
